### ISSUE TITLE
Device infos not available via prometheus stats

### ISSUE THREAD

**Issue by GhostTalker** [UnownHash/Rotom#12]
The information about a device, which is shown in the ui, is not available via prometheus metric.

This information/metric is essential for grafana dashboards and for monitoring the ATV devices.

Can you please add it?

**Comment by GhostTalker** [comment]
Also worker status (free and total) is missing. Only used is available in metrics

**Comment by lenisko** [comment]
https://github.com/UnownHash/Rotom/issues/13 duplicated
