### ISSUE TITLE
Build problem with node 18.15.0

### ISSUE THREAD

**Issue by Pogodenhelder** [UnownHash/Rotom#4]
Building Rotom with node 18.15.0 as per instructions result in the following build error.

https://pastebin.com/qLuqz4wr

**Comment by Fabio1988** [comment]
tried `npm install` too?

**Comment by Pogodenhelder** [comment]
Yes Fabio, tried it.. but still when doing npm run build the errors pop up

**Comment by Pogodenhelder** [comment]
Problem is with the audit fix that will break building.

So best is npm ci --no-audit. then npm run build

**Comment by Fabio1988** [comment]
Solved, `npm audit fix` is a manual command, probably suggested after npm install, never do that ;)
