### ISSUE TITLE
Save Origin and Workers

### ISSUE THREAD

**Issue by plinytheelder** [UnownHash/Rotom#8]
I think this is both an Issue/Feature Request. Currently, Rotom's dashboard and API are dynamic. Origin and Workers can drop off, so real-time monitoring scripts may not pick up if anything is offline. Kasmar is working on updating RDMMonitor to keep track of these changes, so this can provide a workaround. However, if both are restarted "like on a server restart", then everything is empty. Therefore, it would be nice to store Origin and Workers in a database as static placeholders so we can properly monitor workers and ensure uptime.

**Comment by jfberry** [comment]
I'm not sure there is anything you can do if workers a single worker is offline (except complain to your MITM provider about its internal logic); if a device is off-line that is easy enough to detect.
Perhaps RDM Monitor should have a database if it cares about state through reboot? Rotom doesn't need one for any other purpose so adding a database just to support a third party requirement seems a little odd

**Comment by plinytheelder** [comment]
Closing this for now. We discussed and a sqlite database has been implemented for RDMMonitor as a workaround. But have fun answering the emagisk folks. I will direct them directly to @Fabio1988's DM's.
